[package]

name = "haskell-compiler"
version = "0.0.1"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

[[bin]]

name = "haskell-compiler"
path = "src/main.rs"

[dependencies.log]
[dependencies.getopts]
